### ISSUE TITLE
Can't open the app

### ISSUE THREAD

**Issue by MaybeDavey** [Kaplas80/TF3#18]
I did everything correctly, but the app just opens cmd and almost instantly closes.

I tried erasing everything and installing it all again (three times), but it just doesn't work.

**Comment by Kaplas80** [comment]
There is a note in the readme:
**This is a command line application. "Double clicking" on the exe is not enough.**

You have to write the parameters to make it work

**Comment by MaybeDavey** [comment]
Oh. Could you help me, tho? I'm dumb as hell, and i don't know where do I have to write the parameters to make it work (i want to translate Kiwami 2).

**Comment by Kaplas80** [comment]
The steps are:
1. Open a command line prompt
2. Go to the app directory
3. Run the exe with parameters.

For steps 1 and 2, you can search [tutorials in youtube](https://www.youtube.com/watch?v=MBBWVgE0ewk&list=PL6gx4Cwl9DGDV6SnbINlVUd0o2xT4JbMu) and step 3 is explained in the [readme](https://github.com/Kaplas80/TF3#extract-assets).

**Comment by MaybeDavey** [comment]
ty
