### ISSUE TITLE
Game support for thi tool

### ISSUE THREAD

**Issue by BanhMi939** [Kaplas80/TF3#20]
Could i ask is this tool could use to localized yakuza like a dragon or new judgment game?

**Comment by Kaplas80** [comment]
Sorry for the late response, I didn't see the question 🤦🏼‍♂️ 

Those games are already in Spanish, so I won't create plugins for them. But the tool is open sourced and other developers might collaborate and create the plugins.

**Comment by BanhMi939** [comment]
Well, i have no idea about coding so... I find in all of the internet, but only your tools could open .uasset text contained file from another game. But anw, thanks for your reply.
